theirc/cnpp-website

app/pages/404.tsx, app/pages/about.tsx, app/pages/components/Footer.js, app/pages/components/Header.js, app/pages/components/HeroHeader.js, app/pages/contact.tsx, app/pages/index.tsx, app/utils/prefix.js
Added on the prefix clause to all corresponding components
=> Adjust everything to prepend prefix

app/pages/components/AboutContent.js
- Updated styling on About content SBA logo
- Updating text color on "Who we are" heading
=> Updating styling in AboutContent

app/next.config.js, app/pages/404.tsx, app/pages/about.tsx, app/pages/components/Header.js, app/pages/contact.tsx, app/pages/index.tsx
- Removed prefixes that were causing incorrect filepaths
=> fixed prefixing issue

app/pages/components/HeroHeader.js, app/pages/components/HorizontalCard.js, app/pages/components/InfoBlob.js, app/pages/index.tsx
- Added InfoBlob component
- Additional updates to copy
=> Added InfoBlob. Additional copy updates

app/pages/components/ContactComponent.js
Added "got questions" section to bottom of contact page
=> Added got questions section

app/pages/components/HeroHeader.js, app/pages/components/HorizontalCard.js, app/pages/components/StateContent.js
Added IRC provided text and styling updates to home page. 
Left infoBlob in place until subscribe element is ready to go
=> home page edits

app/pages/components/Header.js
Dismissal rings adjusted to use sbaBlue
=> Adjust dismissal rings

app/pages/components/Footer.js
Added additional links to footer
Added email address link
Styling updates
=> Updated footer to include additional pages

app/pages/components/Footer.js, app/styles/globals.css
Added custom CSS fix to spacing of footer nav elements on mobile
=> fixed footer nav item spacing on mobile

app/pages/components/StateContent.js, app/pages/region/[state].js
Added head to state.js
Small style changes to stateContent.js
=> UI component/state page

app/pages/components/Header.js, app/pages/components/ResourcesContent.js, app/pages/resources.tsx
Added the small business resources page and updated the header to point at it.
=> Added the Small business resources page

app/pages/components/InfoBox.js
=> Added functional links and hover state to InfoBox

app/pages/components/GetConnected.js
Needs styling tweaks: mobile friendly and ui-friendly tweaks needed
=> Get-Connected Component

app/pages/components/InfoBox.js, app/pages/components/StateContent.js
Added alts for images on the state pages along with some styling for the tiles and a link on the home page.
=> Add alts for img's, a link and styling

app/pages/components/Footer.js
Added /resources and /region hrefs
=> updated footer hrefs

app/pages/components/contact/ContactComponent.js
fixed iframe styling issue on mobile
=> contact form styling

app/pages/index.tsx
=> removed footer on index.js

app/data.js, app/pages/components/Footer.js, app/pages/components/Header.js, app/pages/components/InfoBlob.js, app/pages/components/InfoBox.js, app/pages/components/StateContent.js, app/pages/region/RegionalLandingContent.js
Made requested changes to individual region pages
Made requested changes to the home page
Replaced footer href to point to preferred sba link
Mapped navigation links (incl. mobile) to data.js
Extracted map images from RegionalLandingContent, moved to data.js, and mapped state cards to data.js
=> Component updates and data revision

app/page-content/AboutPageContent.js, app/page-content/BusinessResourcesContent.js, app/page-content/HomePageContent.js, app/page-content/NewsContent.js, app/page-content/SmallBizOwnerContent.js, app/page-content/StateContent.js, app/pages/components/Header.js, app/pages/components/InfoBox.js, app/pages/components/ResourcesContent.js, app/pages/components/about/AboutContent.js, app/pages/components/news/ModalLayout.js, app/pages/components/news/NewsContent.js, app/pages/components/news/UpdatesAccordion.js, app/pages/region/RegionalLandingContent.js, app/pages/region/[state].js
Extracted data from components to objects within page-content directory
=> Moved data from components to page-content

app/pages/components/StateContent.js, app/pages/components/news/AccordionLayout.js, app/pages/components/news/ModalLayout.js, app/pages/components/news/NewsContent.js
Added in default state for props to resolve pre-rendering issue on build
=> Added in default state to resolve pre-render issue

app/pages/components/Header.js, app/pages/components/news/ModalLayout.js
Lowered Z-index of header component
Changed positioning of modal to display correctly across browsers
=> Modal cross browser bug fixes

app/page-content/SmallBizOwnerContent.js, app/pages/components/news/ModalLayout.js, app/pages/components/news/NewsContent.js
Also, set max width on inner modal container
=> cropped image for modal compatibility 

app/page-content/StateContent.js, app/pages/components/Footer.js, app/pages/components/Header.js, app/pages/components/HeroHeader.js, app/pages/components/ResourcesContent.js, app/pages/components/StateContent.js, app/pages/components/contact/ContactComponent.js, app/pages/components/news/NewsContent.js
Added additional iowa partner, and changed name of existing partner
Added new sba logo to footer
reduced header bottom padding
reduced top margin of components
=> asset and style updates

app/pages/components/GetConnected.js, app/pages/components/StateContent.js, app/pages/components/news/NewsContent.js
Adjusted whitespace on regional pages, regional overview and news page.
Styling updates to widget on mobile
=> Adjust the whitespace, banner image and widget

app/page-content/SmallBizOwnerContent.js, app/pages/components/news/ModalLayout.js, app/pages/components/news/NewsContent.js, app/tailwind.config.js
Changed news content images from bg images to image elements so they can be dynamic
Removed tailwind bg images from config
Updated modal styling
refactored to allow more than 2 business spotlight sections to be on page
=> updates to news page and modal

app/page-content/BusinessResourcesContent.js, app/page-content/HomePageContent.js, app/page-content/NewsContent.js, app/page-content/SmallBizOwnerContent.js, app/page-content/StateContent.js, app/pages/components/news/UpdatesAccordion.js
=> added additional comments to page-content files

app/pages/components/news/UpdatesAccordion.js
Changed news accordion link from <p> to <a> tag
=> Updated news accordion link

app/pages/components/StateContent.js, app/pages/region/[state].js
Added getStaticPaths and getStaticProps to to define dynamic routes at build time
=> fixed routing issue

app/pages/_app.tsx
updated GA script 
Added functionality for tracking internal navigation
=> updated GA script

app/page-content/StateContent.js, app/pages/components/Footer.js, app/pages/components/contact/ContactComponent.js
Added facebook icon and links to footer and contact page
=> UI component/fb link

app/pages/components/ResourcesContent.js
This reverts commit 3ecdc1acb84c8273519a610419413d145860292f.
=> Revert "Update ResourcesContent.js (#90)"
